# -*- coding: utf-8 -*-
"""pitch_type_coors_data_src.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kn3_wjdo2LJq3_RpyrpNNwxJ4ckWBT5z
"""

import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse, Patch
import numpy as np
import pandas as pd


def plot_pitch_success_by_pitcher(player_name, df):
    """
    Plot pitch success rate by pitch type for a single pitcher,
    split by Coors Field vs Other Parks.

    Parameters:
        player_name (str): Full name of pitcher, e.g., "German Marquez"
        df (pd.DataFrame): Dataframe with columns 'pitch_type', 'pitch_success', 'at_coors', 'pitcher_name'
    """
    # Filter to the selected pitcher
    pitcher_df = df[df['pitcher_name'] == player_name]

    if pitcher_df.empty:
        print(f"No data found for pitcher: {player_name}")
        return

    # Compute pitch success rate per pitch type, split by at_coors
    success_rates = pitcher_df.groupby(['pitch_type', 'at_coors'])['pitch_success'].mean().reset_index()

    # Map at_coors to labels
    success_rates['park'] = success_rates['at_coors'].map({1: 'Coors Field', 0: 'Other Parks'})

    # Determine order of pitch types by Coors success rate
    coors_order = success_rates[success_rates['park'] == 'Coors Field'].sort_values('pitch_success')['pitch_type']

    # Pivot table for plotting
    plot_df = success_rates.pivot(index='pitch_type', columns='park', values='pitch_success').reindex(coors_order)

    # Colors
    coors_color = "#33006F"   # Rockies purple
    other_color = "#C0C0C0"   # soft gray

    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))
    plot_df.plot(kind='bar', ax=ax, color=[coors_color, other_color], width=0.8)

    # Background and style
    ax.set_facecolor("#F7F7F7")
    fig.patch.set_facecolor("#F7F7F7")
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)

    # Labels and title
    ax.set_title(
        f"Pitch Success Rate by Pitch Type\n{player_name}: Coors Field vs Other Parks",
        fontsize=14, weight="bold", pad=12
    )
    ax.set_xlabel("Pitch Type", fontsize=12)
    ax.set_ylabel("Pitch Success Rate", fontsize=12)
    ax.set_ylim(0.4, ax.get_ylim()[1])

    ax.yaxis.grid(True, linestyle="", alpha=0.4)
    ax.xaxis.grid(False)
    ax.legend(title="", frameon=False)
    ax.tick_params(axis='x', rotation=0)

    plt.tight_layout()
    plt.show()



def plot_pitch_success_delta(player_name, df, min_pitches=10):
    """
    Plot difference in pitch success rate (Coors Field - Other Parks)
    for an individual pitcher.
    """

    pitcher_df = df[df['pitcher_name'] == player_name].copy()

    if pitcher_df.empty:
        print(f"No data for {player_name}")
        return

    # Optional pitch count filter
    pitch_counts = pitcher_df['pitch_type'].value_counts()
    valid_pitches = pitch_counts[pitch_counts >= min_pitches].index
    pitcher_df = pitcher_df[pitcher_df['pitch_type'].isin(valid_pitches)]

    # Compute success rates
    success_rates = (
        pitcher_df
        .groupby(['pitch_type', 'at_coors'])['pitch_success']
        .mean()
        .reset_index()
    )

    success_rates['park'] = success_rates['at_coors'].map({
        1: 'Coors Field',
        0: 'Other Parks'
    })

    plot_df = success_rates.pivot(
        index='pitch_type',
        columns='park',
        values='pitch_success'
    )

    # Require both parks
    plot_df = plot_df.dropna()

    if plot_df.empty:
        print(f"Not enough Coors vs Other data for {player_name}")
        return

    plot_df['delta'] = plot_df['Coors Field'] - plot_df['Other Parks']
    plot_df = plot_df.sort_values('delta', ascending=True)

    delta_color = "#33006F"
    neg_color = "#C0C0C0"
    bar_colors = [
        delta_color if v >= 0 else neg_color
        for v in plot_df['delta']
    ]

    fig, ax = plt.subplots(figsize=(10, 6))
    plot_df['delta'].plot(
        kind='bar',
        ax=ax,
        color=bar_colors,
        width=0.8
    )

    ax.set_facecolor("#F7F7F7")
    fig.patch.set_facecolor("#F7F7F7")

    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)

    ax.set_title(
        f"Difference in Pitch Success Rate\nCoors Field vs Other Parks — {player_name}",
        fontsize=14,
        weight="bold",
        pad=12
    )

    ax.set_xlabel("Pitch Type", fontsize=12)
    ax.set_ylabel("Difference in Pitch Success Rate", fontsize=12)

    ax.axhline(0, color='black', linewidth=0.8)
    ax.yaxis.grid(True, linestyle="", alpha=0.4)
    ax.xaxis.grid(False)
    ax.tick_params(axis='x', rotation=0)

    plt.tight_layout()
    plt.show()




def plot_pitch_movement_profile(player_name, df, radius=27):
    """
    Plot Savant-style mean ± SD pitch movement for a pitcher,
    differentiating Coors Field (hatched, no fill) vs Other Parks (filled ellipse).
    """

    pitcher_df = df[df['pitcher_name'] == player_name].copy()
    if pitcher_df.empty:
        print(f"No data for {player_name}")
        return

    # Flip horizontal axis to match Savant orientation, convert to inches
    pitcher_df['pfx_x_plot'] = -pitcher_df['pfx_x'] * 12
    pitcher_df['pfx_z_plot'] = pitcher_df['pfx_z'] * 12

    # Vibrant pitch colors
    pitch_colors = {
        'FF': '#FF2D2D', 'SI': '#FF7F0E', 'FC': '#FFD700', 'SL': '#1F77FF',
        'CU': '#00B050', 'CH': '#00CFFF', 'KC': '#8A2BE2', 'FS': '#FF1493',
        'ST': '#8B4513', 'SV': '#7F7F7F'
    }

    fig, ax = plt.subplots(figsize=(9,9))
    subtle_purple = (0.95, 0.90, 1.0, 0.15)  # RGBA tuple: R,G,B in 0-1, alpha last

    fig.patch.set_facecolor(subtle_purple)
    ax.set_facecolor(subtle_purple)

    # Keep track of legend handles for pitch types
    pitch_handles = {}

    # Loop through pitch types and park
    for (pitch, park), group in pitcher_df.groupby(['pitch_type', 'at_coors']):

        if len(group) < 5:
            continue

        color = pitch_colors.get(pitch, 'gray')
        mean_x = group['pfx_x_plot'].mean()
        mean_z = group['pfx_z_plot'].mean()
        std_x = group['pfx_x_plot'].std()
        std_z = group['pfx_z_plot'].std()

        # Ellipse style
        if park == 1:  # Coors Field
            facecolor = 'none'      # no fill
            hatch_pattern = '///'
        else:          # Other Parks
            facecolor = color       # filled
            hatch_pattern = None

        ellipse = Ellipse(
            (mean_x, mean_z),
            width=3*std_x,
            height=3*std_z,
            facecolor=facecolor,
            edgecolor=color,
            alpha=0.5,
            hatch=hatch_pattern,
            linewidth=2
        )
        ax.add_patch(ellipse)

        # Mean point (always circle)
        if park == 1:  # Coors Field
          point_facecolor = 'white'
        else:
          point_facecolor = color

        ax.scatter(mean_x, mean_z,
                   color=point_facecolor,
                   edgecolor='black',
                   s=120,
                   marker='o')

        # Save one handle per pitch type for legend
        if pitch not in pitch_handles:
            pitch_handles[pitch] = Patch(facecolor=color, edgecolor='black', label=pitch)

    # Circular grid
    for r in range(5, radius+1, 5):
        circle = plt.Circle((0,0), r, color='gray', fill=False, linestyle='--', alpha=0.6)
        ax.add_artist(circle)

    ax.axhline(0, linewidth=1, alpha=0.6)
    ax.axvline(0, linewidth=1, alpha=0.6)

    ax.set_xlim(-radius, radius)
    ax.set_ylim(-radius, radius)
    ax.set_aspect('equal', adjustable='box')

    ax.set_xlabel("Horizontal Movement (inches)")
    ax.set_ylabel("Vertical Movement (inches)")
    ax.set_title(f"Pitch Movement Profile: {player_name}",
                 fontsize=14, weight='bold')

    # Create combined legend
    park_patches = [
        Patch(facecolor='white', edgecolor='black', hatch='///', label='Coors Field'),
        Patch(facecolor='black', edgecolor='black', alpha=0.5, label='Other Parks')
    ]

    combined_handles = list(pitch_handles.values()) + [
        Patch(facecolor='white', edgecolor='black', hatch='///', label='Coors Field'),
        Patch(facecolor='gray', edgecolor='black', alpha=0.5, label='Other Parks')
    ]

    ax.legend(handles=combined_handles, title="Pitch Type & Park", frameon=False, bbox_to_anchor=(1.05, 1))

    plt.tight_layout()
    plt.show()


import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Ellipse, Patch

def plot_pitch_movement_profile_avg(throw_hand, df, radius=27):
    """
    Plot combined Savant-style mean ± SD pitch movement for ALL pitchers
    of a given throwing hand ('R' or 'L'),
    differentiating Coors Field vs Other Parks.
    """

    pitcher_df = df[df['p_throws'] == throw_hand].copy()
    if pitcher_df.empty:
        print(f"No data for throwing hand: {throw_hand}")
        return

    # Flip horizontal axis to match Savant orientation, convert to inches
    pitcher_df['pfx_x_plot'] = -pitcher_df['pfx_x'] * 12
    pitcher_df['pfx_z_plot'] = pitcher_df['pfx_z'] * 12

    pitch_colors = {
        'FF': '#FF2D2D', 'SI': '#FF7F0E', 'FC': '#FFD700', 'SL': '#1F77FF',
        'CU': '#00B050', 'CH': '#00CFFF', 'KC': '#8A2BE2', 'FS': '#FF1493',
        'ST': '#8B4513', 'SV': '#7F7F7F'
    }

    fig, ax = plt.subplots(figsize=(9,9))
    subtle_purple = (0.95, 0.90, 1.0, 0.15)
    fig.patch.set_facecolor(subtle_purple)
    ax.set_facecolor(subtle_purple)

    pitch_handles = {}

    for (pitch, park), group in pitcher_df.groupby(['pitch_type', 'at_coors']):

        if len(group) < 20:   # increase threshold since now aggregated
            continue

        color = pitch_colors.get(pitch, 'gray')

        mean_x = group['pfx_x_plot'].mean()
        mean_z = group['pfx_z_plot'].mean()
        std_x = group['pfx_x_plot'].std()
        std_z = group['pfx_z_plot'].std()

        if park == 1:
            facecolor = 'none'
            hatch_pattern = '///'
        else:
            facecolor = color
            hatch_pattern = None

        ellipse = Ellipse(
            (mean_x, mean_z),
            width=2*std_x,
            height=2*std_z,
            facecolor=facecolor,
            edgecolor=color,
            alpha=0.5,
            hatch=hatch_pattern,
            linewidth=2
        )
        ax.add_patch(ellipse)

        if park == 1:
            point_facecolor = 'white'
        else:
            point_facecolor = color

        ax.scatter(mean_x, mean_z,
                   color=point_facecolor,
                   edgecolor='black',
                   s=120,
                   marker='o')

        if pitch not in pitch_handles:
            pitch_handles[pitch] = Patch(facecolor=color, edgecolor='black', label=pitch)

    # Circular grid
    for r in range(5, radius+1, 5):
        circle = plt.Circle((0,0), r, color='gray',
                            fill=False, linestyle='--', alpha=0.6)
        ax.add_artist(circle)

    ax.axhline(0, linewidth=1, alpha=0.6)
    ax.axvline(0, linewidth=1, alpha=0.6)

    ax.set_xlim(-radius, radius)
    ax.set_ylim(-radius, radius)
    ax.set_aspect('equal', adjustable='box')

    hand_label = "Right-Handed Pitchers" if throw_hand == 'R' else "Left-Handed Pitchers"

    ax.set_xlabel("Horizontal Movement (inches)")
    ax.set_ylabel("Vertical Movement (inches)")
    ax.set_title(f"Pitch Movement Profile: {hand_label}",
                 fontsize=14, weight='bold')

    combined_handles = list(pitch_handles.values()) + [
        Patch(facecolor='white', edgecolor='black', hatch='///', label='Coors Field'),
        Patch(facecolor='gray', edgecolor='black', alpha=0.5, label='Other Parks')
    ]

    ax.legend(handles=combined_handles,
              title="Pitch Type & Park",
              frameon=False,
              bbox_to_anchor=(1.05, 1))

    plt.tight_layout()
    plt.show()


def pitch_movement_delta(player_name, df):
    """
    Compute Euclidean distance between mean pfx_x / pfx_z at Coors vs Other Parks
    for each pitch type for a given pitcher.

    Returns a DataFrame with pitch_type, coors_mean_x, coors_mean_z, other_mean_x,
    other_mean_z, and euclidean_delta.
    """

    pitcher_df = df[df['pitcher_name'] == player_name].copy()
    if pitcher_df.empty:
        print(f"No data for {player_name}")
        return None

    # Convert to inches and flip horizontal to match Savant orientation
    pitcher_df['pfx_x_plot'] = -pitcher_df['pfx_x'] * 12
    pitcher_df['pfx_z_plot'] = pitcher_df['pfx_z'] * 12

    results = []

    for pitch, group in pitcher_df.groupby('pitch_type'):
        coors = group[group['at_coors'] == 1]
        other = group[group['at_coors'] == 0]

        if len(coors) < 5 or len(other) < 5:
            continue  # skip if not enough samples

        coors_mean_x = coors['pfx_x_plot'].mean()
        coors_mean_z = coors['pfx_z_plot'].mean()

        other_mean_x = other['pfx_x_plot'].mean()
        other_mean_z = other['pfx_z_plot'].mean()

        euclidean_delta = np.sqrt(
            (coors_mean_x - other_mean_x)**2 + (coors_mean_z - other_mean_z)**2
        )

        results.append({
            'pitch_type': pitch,
            'coors_mean_x': coors_mean_x,
            'coors_mean_z': coors_mean_z,
            'other_mean_x': other_mean_x,
            'other_mean_z': other_mean_z,
            'euclidean_delta': euclidean_delta
        })

    return pd.DataFrame(results).sort_values('euclidean_delta', ascending=False)



def league_pitch_movement_delta_by_hand(df, hand_col='p_throws', min_samples=20):
    """
    Compute average Euclidean distance between mean pitch movement at Coors vs Other Parks
    per pitch type across ALL pitchers, separated by handedness.

    Returns:
        DataFrame with handedness, pitch_type, and euclidean_delta
    """

    data = df.copy()

    # Convert to inches and match Savant orientation
    data['pfx_x_plot'] = -data['pfx_x'] * 12
    data['pfx_z_plot'] = data['pfx_z'] * 12

    results = []

    for hand, hand_group in data.groupby(hand_col):

        for pitch, group in hand_group.groupby('pitch_type'):

            coors = group[group['at_coors'] == 1]
            other = group[group['at_coors'] == 0]

            if len(coors) < min_samples or len(other) < min_samples:
                continue

            coors_mean_x = coors['pfx_x_plot'].mean()
            coors_mean_z = coors['pfx_z_plot'].mean()

            other_mean_x = other['pfx_x_plot'].mean()
            other_mean_z = other['pfx_z_plot'].mean()

            euclidean_delta = np.sqrt(
                (coors_mean_x - other_mean_x)**2 +
                (coors_mean_z - other_mean_z)**2
            )

            results.append({
                'handedness': hand,
                'pitch_type': pitch,
                'coors_mean_x': coors_mean_x,
                'coors_mean_z': coors_mean_z,
                'other_mean_x': other_mean_x,
                'other_mean_z': other_mean_z,
                'euclidean_delta': euclidean_delta
            })

    return pd.DataFrame(results).sort_values(
        ['handedness', 'euclidean_delta'],
        ascending=[True, False]
    )

